config/routes.rb
Rails.application.routes.draw do
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email, only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset, only: [ :new, :edit, :create, :update ]
    resource :account, only: [ :show ], controller: "account"
  end
  get "chats", to: "chats#index"
  get "docs", to: "docs#index"
  resources "forum_posts", only: [ :index, :new, :create ]
  post "/chats/send", to: "chats#send_message"

  root "home#index"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div id="flash" class="flex flex-col justify-center items-center mt-2">
    <% if (notice = flash[:notice]) %>
      <p class="flash notice" id="notice"><%= notice %></p>
    <% end %>
    <% if (alert = flash[:alert]) %>
      <p class="flash alert" id="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header
  data-turbo-permanent class="flex justify-between">
  <div class="py-[4px]">
    <button
      id="toggle-sidebar-button"
      title="sidebar toggle"
      type="button"
      class="icon-button dark px-2 py-[4px] h-full"
      data-controller="sidebar-toggle"
      data-action="click->sidebar-toggle#toggle"
    >
      <%= inline_svg_tag "bars.svg", class: "h-full max-w-6" %>
    </button>
  </div>
  <div class="h-full flex items-center">
      <% if Current.user %>
        <%= link_to Current.user.email,
                    identity_account_path,
                    class: "icon-button dark px-4 py-2" %>
      <% end %>
    <%= render "shared/dark_mode_toggle" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Docchat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-cache-control" content="no-cache">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag "application" %>
    <%= vite_javascript_tag "application" %>

    <script>
      // Prevent Firefox FOUC (flash of unstyled content)
      // See https://stackoverflow.com/a/64158043
      let FF_FOUC_FIX;
    </script>

  </head>

  <body data-turbo-prefetch="false" data-theme="aqua">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<% content_for :content do %>
  <%= render "layouts/header" %>
  <div class="main-split">
    <div>
      <%= render "layouts/sidebar/sidebar" %>
    </div>
    <main>
      <%= render "layouts/flash" %>
      <%= yield %>
    </main>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/signed_out.html.erb
<% content_for :content do %>
  <div class="bg-primary-bg h-svh flex flex-col items-center justify-center">
    <%= render "layouts/flash" %>
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application" %>